#!/bin/bash
# Synthos Self-Evolution Daily Probe
# Gate: G7 — 每日05:00执行，评估系统健康状态并触发改进
# Output: 写入 outputs/evolution/daily-$(date +%Y%m%d).md

SYNTHOS="/media/yakeworld/sda2/Synthos"
OUTDIR="$SYNTHOS/outputs/evolution"
DATE=$(date +%Y%m%d)
REPORT="$OUTDIR/daily-${DATE}.md"
GOLDEN="$SYNTHOS/tests/golden_test.py"

mkdir -p "$OUTDIR"

echo "# Synthos 每日自检 — $DATE" > "$REPORT"
echo "" >> "$REPORT"

# G1: 结构完整性 — 7原子检查
echo "## G1: 核心原子结构" >> "$REPORT"
PASS=0
TOTAL=6
for atom in knowledge-acquisition knowledge-extraction association-discovery hypothesis-generation argument-expression viewpoint-verification; do
    SKILL="$SYNTHOS/skills/core/$atom/SKILL.md"
    if [ -f "$SKILL" ]; then
        V=$(grep -c "^version:" "$SKILL")
        S=$(grep -c "^signature:" "$SKILL")
        IO=$(grep -c "IO_CONTRACT\|^io_contract:" "$SKILL")
        if [ "$V" -gt 0 ] && [ "$S" -gt 0 ] && [ "$IO" -gt 0 ]; then
            echo "- ✅ $atom" >> "$REPORT"
            PASS=$((PASS+1))
        else
            echo "- ⚠️ $atom (v=$V sig=$S io=$IO)" >> "$REPORT"
        fi
    else
        echo "- ❌ $atom (NOT FOUND)" >> "$REPORT"
    fi
done
echo "  Score: $PASS/$TOTAL" >> "$REPORT"
echo "" >> "$REPORT"

# G2: IO_CONTRACT 覆盖率
echo "## G2: IO_CONTRACT 覆盖率" >> "$REPORT"
TOTAL_SKILLS=$(find "$SYNTHOS" -name "*SKILL.md" 2>/dev/null | wc -l)
WITH_IO=$(grep -rl "IO_CONTRACT\|^io_contract:" $(find "$SYNTHOS" -name "*SKILL.md") 2>/dev/null | wc -l)
COV=$(echo "scale=1; $WITH_IO * 100 / $TOTAL_SKILLS" | bc)
echo "- Skills: $TOTAL_SKILLS, with IO_CONTRACT: $WITH_IO (${COV}%)" >> "$REPORT"
echo "" >> "$REPORT"

# G6: Golden test
echo "## G6: Golden Test" >> "$REPORT"
if [ -f "$GOLDEN" ]; then
    python3 "$GOLDEN" >> "$REPORT" 2>&1
else
    echo "- ⚠️ golden_test.py not found" >> "$REPORT"
fi
echo "" >> "$REPORT"

# 论文管线状态
echo "## 论文管线" >> "$REPORT"
PAPERS=$(ls -d "$SYNTHOS/outputs/papers/"*/ 2>/dev/null | wc -l)
echo "- 活跃论文: $PAPERS 篇" >> "$REPORT"
echo "" >> "$REPORT"

echo "---" >> "$REPORT"
echo "_Generated by self-evolution cron at $(date)_" >> "$REPORT"

cat "$REPORT"
